version: '2'
services:
  web:
    build: ./symfony
    ports:
    - "8080:8000"
    volumes:
    - ..:/var/www
    - logvolume01:/var/log
    links:
    - mysql
    container_name: craft_web
    command: php bin/console server:run 172.16.1.2:8000
    networks:
      app_net:
        ipv4_address: 172.16.1.2
  mysql:
    build: ./mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: craft
    container_name: craft_mysql
    networks:
          app_net:
            ipv4_address: 172.16.1.3


networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24
        gateway: 172.16.1.1
volumes:
  logvolume01: {}